### ISSUE TITLE
Markijal_Home[Sprint 1]

### ISSUE THREAD

**Issue by dendysrprdn** [SI-RPL-2022/SI4308_E_Markijal#1]
Pembuatan halaman home

**Comment by Alifurfan** [comment]
![image](https://user-images.githubusercontent.com/32005233/163552298-a7b61d2d-acbc-453e-8e8a-141fc38fbf83.png)

**Comment by dendysrprdn** [comment]
????????

**Comment by Lurax21** [comment]
ngecit

**Comment by dendysrprdn** [comment]
?????

**Comment by Alifurfan** [comment]
ngoding nya kemaren bang
